name: Deploy Quarkus Project to Azure Function App

on:
  push:
    branches:
        - main

env:
  AZURE_FUNCTIONAPP_NAME: 'quarkus-azure-functionn-1703850888742'
  POM_XML_DIRECTORY: '.'
  JAVA_VERSION: '11'
  GRAALVM_VERSION: '21.1.0'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'Set up GraalVM'
      run: |
        GRAALVM_URL=https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-${{ env.GRAALVM_VERSION }}/graalvm-ce-java${{ env.JAVA_VERSION }}-linux-amd64-${{ env.GRAALVM_VERSION }}.tar.gz
        wget -q $GRAALVM_URL -O graalvm.tar.gz
        tar -xzf graalvm.tar.gz
        export GRAALVM_HOME=$(pwd)/graalvm-ce-java${{ env.JAVA_VERSION }}-${{ env.GRAALVM_VERSION }}
        export PATH=$GRAALVM_HOME/bin:$PATH
        gu install native-image

    - name: 'Build Native Executable Using Mvn'
      shell: bash
      run: |
        export GRAALVM_HOME=$(pwd)/graalvm-ce-java${{ env.JAVA_VERSION }}-${{ env.GRAALVM_VERSION }}
        export PATH=$GRAALVM_HOME/bin:$PATH
        pushd './${{ env.POM_XML_DIRECTORY }}'
        mvn clean package -Pnative
        popd

    - name: 'List target directory'
      run: ls -l ./target

    - name: 'Run Azure Functions Action'
      uses: azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: './target/azure-functions/quarkus-azure-functionn-1703850888742'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        respect-pom-xml: true