name: Deploy Quarkus Project to Azure Function App

on:
  [push]

env:
  AZURE_FUNCTIONAPP_NAME: 'quarkus-azure-functionn-1703850888742'
  POM_XML_DIRECTORY: '.'
  JAVA_VERSION: '11'
  GRAALVM_VERSION: '21.1.0'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup GraalVM
      uses: DeLaGuardo/setup-graalvm@3
      with:
        graalvm-version: 'java${{ env.JAVA_VERSION }}-${{ env.GRAALVM_VERSION }}'
        java: 'java${{ env.JAVA_VERSION }}'
        native-image: 'true'

    - name: 'Build Native Executable Using Mvn'
      shell: bash
      run: |
        pushd './${{ env.POM_XML_DIRECTORY }}'
        mvn clean package -Pnative
        popd

    - name: 'List target directory'
      run: ls -l ./target
      
    - name: 'Run Azure Functions Action'
      uses: azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: './target/azure-functions/quarkus-azure-functionn-1703850888742'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        respect-pom-xml: true

# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples